---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 86400

- name: Install Prequisites
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
  

- name: Create keyrings dir
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'  
    
   
- name: Download Docker GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repo
  apt_repository:
    repo: "deb [arch={{ ansible_architecture | regex_replace('aarch64','arm64') | regex_replace('x86_64','amd64') }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    filename: docker
    state: present

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Ensure docker group exists
  group:
    name: docker
    state: present

- name: Add {{ new_user }} to docker group
  user:
    name: "{{ new_user }}"
    groups: docker
    append: yes
  
- name: Ensure Docker started and enabled
  systemd:
    name: docker
    state: started
    enabled: yes
  notify: restart docker 
    
